### PR TITLE
Fix screens navigation

### PR DESCRIPTION
**Pull request by Bahatiroben**
the same issue with tester pack.
duka locator and group repayments have * and # as options of navigating the screen. I have changed them to 77 and 44 respectively.

duka locator: https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit

GROUP leader RW: account number: **28951336**

group repayments RW: https://telerivet.com/p/8799a79f/service/SV215b0cbe269df25d
group repayments: KE: https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit 

these services should behave exactly as before but with * and # replaced with 77 and 44 respectively

### CODE REVIEW

**Review by nyabongo — CHANGES_REQUESTED** [review]
Since this is not a hotfix lets merge this through develop instead of master

**Comment by Bahatiroben** [comment]
> Since this is not a hotfix lets merge this through develop instead of master

alright. make sense since we will even be deplyoying very soon.

**Comment by nyabongo** [comment]
Any reason this is sill targeting master?

**Comment by Bahatiroben** [comment]
> Any reason this is sill targeting master?

have had branched off master, since the service was live. was not urgent though.

**Comment by Bahatiroben** [comment]
> > Any reason this is sill targeting master?
> 
> have had branched off master, since the service was live. was not urgent though.

Have changed the base to develop since we have back merged master into develop.

**Review by nyabongo — APPROVED** [review]

**Review by shejasabin — APPROVED** [review]

**Pull request merged**
